# -*- coding: utf-8 -*-
#
# notnews documentation build configuration file, created by
# sphinx-quickstart on Tue Jan 23 19:17:03 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath("../.."))

# Import project metadata from pyproject.toml
try:
    import tomllib  # Python 3.11+
except ImportError:
    try:
        import tomli as tomllib  # fallback for older Python
    except ImportError:
        import toml as tomllib_fallback

        def load_toml(fp):
            return tomllib_fallback.load(fp)

        tomllib = type("tomllib", (), {"load": load_toml})()

project_dir = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
pyproject_path = os.path.join(project_dir, "pyproject.toml")

try:
    with open(pyproject_path, "rb") as f:
        pyproject_data = tomllib.load(f)
    project_metadata = pyproject_data["project"]
except (FileNotFoundError, KeyError, AttributeError):
    # Fallback values if pyproject.toml is not found or can't be parsed
    project_metadata = {
        "name": "notnews",
        "version": "0.2.3",
        "authors": [{"name": "Suriyan Laohaprapanon, Gaurav Sood"}],
        "description": "Predict Soft News",
    }


def generate_dynamic_content():
    """Generate dynamic content files from pyproject.toml metadata."""
    shared_dir = os.path.join(os.path.dirname(__file__), "_shared")
    
    # Extract Python version requirements
    requires_python = project_metadata.get("requires-python", ">=3.11")
    
    # Parse Python versions from classifiers
    python_versions = []
    for classifier in project_metadata.get("classifiers", []):
        if classifier.startswith("Programming Language :: Python :: 3."):
            version = classifier.split(" :: ")[-1]
            if version.replace(".", "").isdigit():  # e.g., "3.11", "3.12"
                python_versions.append(version)
    
    if not python_versions:
        python_versions = ["3.11", "3.12", "3.13"]  # fallback
    
    # Generate installation.md with dynamic content
    installation_content = f"""## Installation

Installation is as easy as typing in:

```bash
pip install {project_metadata.get('name', 'notnews')}
```

For faster installation using UV:

```bash
uv add {project_metadata.get('name', 'notnews')}
```

### Optional Dependencies

For LLM-based classification with Claude and OpenAI:

```bash
pip install {project_metadata.get('name', 'notnews')}[llm]
# or
uv add {project_metadata.get('name', 'notnews')} --extra llm
```

### Requirements

- Python {', '.join(python_versions)}
- scikit-learn 1.3+ (models trained with sklearn 0.22+ are automatically compatible)
- pandas, numpy, nltk, and other standard scientific Python packages

### LLM Requirements (Optional)

- anthropic>=0.18.0 (for Claude)
- openai>=1.12.0 (for OpenAI)

### Compatibility

This package includes automatic compatibility layers to ensure models trained with older scikit-learn versions (0.22+) work seamlessly with modern scikit-learn versions (1.3-1.5). Version warnings from scikit-learn are expected and harmless."""
    
    installation_path = os.path.join(shared_dir, "installation.md")
    with open(installation_path, "w") as f:
        f.write(installation_content)


# Generate dynamic content at documentation build time
generate_dynamic_content()


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx_autodoc_typehints",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx_copybutton",
    "myst_parser",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = "index"

# General information about the project.
project = project_metadata["name"]
copyright = "2025, Suriyan Laohaprapanon, Gaurav Sood"
author = ", ".join([a["name"] for a in project_metadata["authors"]])

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = project_metadata["version"]
# The full version, including alpha/beta/rc tags.
release = project_metadata["version"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Suppress specific warnings
suppress_warnings = ["myst.header"]


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"

# Furo theme options
html_theme_options = {
    "source_repository": "https://github.com/notnews/notnews",
    "source_branch": "master",
    "source_directory": "docs/source/",
    "sidebar_hide_name": False,
    "navigation_with_keys": True,
    "top_of_page_button": "edit",
}

html_title = f"{project} {release}"
html_logo = None
html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

# Type hints settings
typehints_defaults = 'comma'
typehints_use_signature = True
typehints_use_signature_return = True
autodoc_typehints_description_target = 'documented'

# MyST settings
myst_enable_extensions = [
    'colon_fence',
    'deflist',
    'dollarmath',
    'fieldlist',
    'html_admonition',
    'html_image',
    'replacements',
    'smartquotes',
    'strikethrough',
    'substitution',
    'tasklist',
]

# MyST configuration
myst_suppress_warnings = ["myst.header"]

# Copy button configuration
copybutton_prompt_text = r">>> |\.\.\. |\$ "
copybutton_prompt_is_regexp = True
copybutton_line_continuation_character = "\\"
copybutton_here_doc_delimiter = "EOF"


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "PyDomainsdoc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "notnews.tex",
        "notnews Documentation",
        "Suriyan Laohaprapanon, Gaurav Sood",
        "manual",
    ),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "notnews", "notnews Documentation", [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "notnews",
        "notnews Documentation",
        author,
        "notnews",
        "Predict the category of content hosted by a domain.",
        "Miscellaneous",
    ),
]
